<?php

use Application\Form\OrganizationForm;
use Zend\Form\View\Helper\FormLabel;

$this->headTitle('Organization Create');

/** @var OrganizationForm $form */
$form = $this->form;
$form
    ->prepare()
    ->setAttributes([
        'action' => $this->url('organization/create'),
        'method' => 'post',
        'class' => 'form'
    ]);

/** @var FormLabel $formLabel */
$formLabel = $this->plugin('formLabel');
$name = $form->get('name');
?>

<h1>Nouvelle organisation</h1>
<?= $this->form()->openTag($form); ?>
<div class="form-group">
    <?= $formLabel($name); ?>
    <?= $this->formInput($name); ?>
    <?= $this->formElementErrors($name); ?>
</div>


<?= $this->formElement($form->get('security')) ?>
<?= $this->formElement($form->get('submit')) ?>
<?= $this->form()->closeTag() ?>


