<?php

use Application\Form\OrganizationForm;
use Zend\Form\View\Helper\FormLabel;

$this->headTitle('Organization Update');

/** @var OrganizationForm $form */
$form = $this->form;
$form
    ->prepare()
    ->setAttributes([
        'action' => $this->url('organization/edit', [], [], true),
        'method' => 'post',
        'class' => 'form'
    ]);

/** @var FormLabel $formLabel */
$formLabel = $this->plugin('formLabel');
$name = $form->get('name');
$userSelect = $form->get('leader');

?>

<h1>Nouvel utilisateur</h1>
<?= $this->form()->openTag($form); ?>
<div class="form-group">
    <?= $formLabel($name); ?>
    <?= $this->formInput($name); ?>
    <?= $this->formElementErrors($name); ?>
</div>

<div class="form-group">
    <?= $formLabel($userSelect); ?>
    <?= $this->formSelect($userSelect); ?>
    <?= $this->formElementErrors($userSelect); ?>
</div>

<?= $this->formElement($form->get('security')) ?>
<?= $this->formElement($form->get('submit')) ?>
<?= $this->form()->closeTag() ?>


