<?php

namespace Application\Repository;

use Application\Entity\Meetup;
use Doctrine\ORM\EntityRepository;

/**
 * MeetupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method Meetup[]|array|null findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 * @method Meetup findOneBy(array $criteria, array $orderBy = null)
 */
class MeetupRepository extends EntityRepository
{
}
