<?php

namespace Application\Repository;

use Application\Entity\Organization;
use Doctrine\ORM\EntityRepository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method Organization[]|array|null findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 * @method Organization findOneBy(array $criteria, array $orderBy = null)
 */
final class OrganizationRepository extends EntityRepository
{
}
