<?= $this->doctype() ?>

<html lang="fr">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Meetup Project')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker3.css" />

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/helper.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28"
                     alt="Zend Framework <?= \Application\Module::VERSION ?>"/>
                &nbsp;Meetup Project
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="<?= $this->url() == $this->url('home') ? "active": "" ?>">
                    <a href="<?= $this->url('home') ?>">Home</a>
                </li>
                <li class="<?= $this->url() == $this->url('meetup_create') ? "active": "" ?>">
                    <a href="<?= $this->url('meetup_create') ?>">Ajouter un Meetup</a>
                </li>
                <li class="<?= $this->url() == $this->url('meetup_list') ? "active": "" ?>">
                    <a href="<?= $this->url('meetup_list') ?>">Voir les Meetup</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->partial('application/flashbag.phtml', ['flash' => $this->flashMessenger()]) ?>
    <?= $this->content ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
