<?php

use Application\Entity\User;

/** @var User $user */
$user = $this->user;
?>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><?= $user->getUsername() ?></div>
    <div class="panel-body">
        <?php if ($user->getOrganizedMeetups()->count() > 0): ?>
            L'utilisateur est organisateur des meetups suivants :
            <ul>
                <?php foreach ($user->getOrganizedMeetups() as $organizedMeetup): ?>
                    <li>
                        <a href="<?= $this->url('meetup/detail', ['id' => $organizedMeetup->getId()]) ?>">
                            <?= $organizedMeetup->getTitle() ?>
                        </a>
                    </li>
                <?php endforeach; ?>

            </ul>
        <?php else: ?>
            L'utilisateur n'est organisateur d'aucun meetup
        <?php endif ?>
    </div>

</div>


