<?php

use Application\Form\UserForm;
use Zend\Form\View\Helper\FormLabel;

$this->headTitle('User Update');

/** @var UserForm $form */
$form = $this->form;
$form
    ->prepare()
    ->setAttributes([
        'action' => $this->url('user/edit', [], [], true),
        'method' => 'post',
        'class' => 'form'
    ]);

/** @var FormLabel $formLabel */
$formLabel = $this->plugin('formLabel');
$username = $form->get('username');
?>

<h1>Nouvel utilisateur</h1>
<?= $this->form()->openTag($form); ?>
<div class="form-group">
    <?= $formLabel($username); ?>
    <?= $this->formInput($username); ?>
    <?= $this->formElementErrors($username); ?>
</div>


<?= $this->formElement($form->get('security')) ?>
<?= $this->formElement($form->get('submit')) ?>
<?= $this->form()->closeTag() ?>


