<?php

use Application\Form\MeetupForm;
use Zend\Form\View\Helper\FormLabel;

$this->headTitle('Create');

/** @var MeetupForm $form */
$form = $this->form;
$form
    ->prepare()
    ->setAttributes([
        'action' => $this->url('meetup/edit', [], [], true),
        'method' => 'post',
        'class' => 'form'
    ]);

/** @var FormLabel $formLabel */
$formLabel = $this->plugin('formLabel');
$title = $form->get('title');
$description = $form->get('description');
$startDate = $form->get('start_date');
$endDate = $form->get('end_date');
$userSelect = $form->get('organizer');

?>

<h1>Contact</h1>
<?= $this->form()->openTag($form); ?>
<div class="form-group">
    <?= $formLabel($title); ?>
    <?= $this->formInput($title); ?>
    <?= $this->formElementErrors($title); ?>
</div>

<div class="form-group">
    <?= $formLabel($description); ?>
    <?= $this->formTextArea($description); ?>
    <?= $this->formElementErrors($description); ?>
</div>

<div class="form-group">
    <?= $formLabel($startDate); ?>
    <?= $this->formText($startDate); ?>
    <?= $this->formElementErrors($startDate); ?>
</div>

<div class="form-group">
    <?= $formLabel($endDate); ?>
    <?= $this->formText($endDate); ?>
    <?= $this->formElementErrors($endDate); ?>
</div>

<div class="form-group">
    <?= $formLabel($userSelect); ?>
    <?= $this->formSelect($userSelect); ?>
    <?= $this->formElementErrors($userSelect); ?>
</div>

<?= $this->formElement($form->get('security')) ?>
<?= $this->formElement($form->get('submit')) ?>
<?= $this->form()->closeTag() ?>


