<h1>Bienvenue !</h1>

<p>Ce projet contient des <b>Meetup</b> et des <b>Users</b>.</p>

<p>Chaque <b>Meetup</b> contient un <b>Organizer (User)</b> ainsi que d'autres informations.</p>

<p>Chaque <b>User</b> contient une liste de <b>OrganizedMeetups (Meetup)</b> ainsi que d'autres informations.</p>

<p>Pour bien commencer, il est conseillé de <b><a href="<?= $this->url('user/create') ?>">créer un utilisateur</a></b></p>