<?php

use Application\Entity\Meetup;

/** @var Meetup $meetup */
?>

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Meetups</div>
    <div class="panel-body">
        <p>
            Les différents meetups sont listés ici <br>
            <a href="<?= $this->url('meetup/create') ?>" class="btn btn-info">Ajouter un Meetup</a>

        </p>
    </div>

    <!-- Table -->
    <table class="table table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Titre</th>
            <th>Date de début</th>
            <th>Date de fin</th>
            <th>Organisateur</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($this->meetups as $meetup): ?>
            <tr>
                <td><?= $meetup->getId() ?></td>
                <td><?= $meetup->getTitle() ?></td>
                <td><?= $meetup->getStartDate()->format('d/m/Y') ?></td>
                <td><?= $meetup->getEndDate()->format('d/m/Y') ?></td>
                <td><?= $meetup->getOrganizer()->getUsername() ?></td>
                <td>
                    <a href="<?= $this->url('meetup/detail', ['id' => $meetup->getId()]) ?>" class="btn btn-info">Afficher</a>
                    <a href="<?= $this->url('meetup/edit', ['id' => $meetup->getId()]) ?>" class="btn btn-warning">Editer</a>
                    <a href="<?= $this->url('meetup/delete', ['id' => $meetup->getId()]) ?>" class="btn btn-danger">Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>


